#==== VillagerVendor by Wehttam664 ====#
#======== Plugin Configuration ========#
# debugID:               The block ID for the debug block. Defaults to 7 (Bedrock).
# entityIDTool:          The tool used to gather something's unique entity ID. (Doesn't stop players from damaging the entity.)
# displayVendorMessage:  Should vendors display a chat message upon interaction? Defaults to true.
# vendormessages:        Messages the vendor speaks when interacted with.

settings:
   debugID: 7
   entityIDTool: 288
   displayVendorMessage: true
   vendormessages:
      - 'Something look interesting?'
      - 'Another day another dollar.'
      - 'Take a look around. You might find something.'
      - 'You have money? I will give you something for it.' 
            
