name: VillagerVendor
main: net.mayateck.VillagerVendor.VillagerVendor
version: '0.00.01'

commands:
   vendor:
      description: VillagerVendor commands.
      usage: /vendor <sub-command> <args>
      permission: villagervendor.general
      permission-message: 'You do not have permission for that, sorry.'
   shopitem:
      description: 'Modifies item books.'
      usage: '/shopitem [sub-command] <args>'
      permission: villagervendor.shopitem
      permission-message: 'You do not have permission for that, sorry.'

permissions:
   villagervendor.*:
      description: 'Gives full access to VillagerVendor.'
      children:
         villagervendor.general: false
         villagervendor.admin: false
         villagervendor.use: true
   villagervendor.general:
      description: 'General VillagerVendor commands. (Info, help, etc.)'
      children:
         villagervendor.general.info: true
         villagervendor.general.help: true
         villagervendor.general.debug: false
         villagervendor.general.getid: true
   villagervendor.admin:
      description: 'Admin commands for VillagerVendor.'
      children:
         villagervendor.admin.create: false
         villagervendor.admin.remove: false
         villagervendor.admin.reloadconfig: false
         villagervendor.admin.reloadvendors: false
   villagervendor.use:
      description: 'Use of Villager Vendors.'
      children:
         villagervendor.use.buy: true
         villagervendor.use.sell: true
         villagervendor.use.view: true
